---
title: "Simple document"
author: Ifrah
date: 2021-09-16
output: 
   html_document: 
      toc: TRUE
      toc_float: TRUE
      code_folding: hide
---

I'm an R Markdown document! 

# Section 1

Here's a **code chunk** that samples from 
a _normal distribution_:

```{r, message = FALSE}
samp = rnorm(500)
length(samp)
```

# Section 2

I can take the mean of the sample, too!
The mean is `r mean(samp)`.

# Section 3

Let's write a new code chunk.

This code chunk imports the `tidyverse', creates a data frame and makes a histogram.

```{r, message = FALSE}
library(tidyverse)

set.seed(1234)

plot_df = 
  tibble(
    x = rnorm(1000, sd = 0.5),
    y = 1 + 2*x + rnorm(1000)
  )

ggplot(plot_df, aes(x = x)) + geom_histogram()
ggplot(plot_df, aes(x = x, y = y)) + geom_point()
```

# Learning Assessment

```{r, message = FALSE}
learning_df =
  tibble(
    sample = rnorm(500, mean = 1),
    gr_than_0 = sample > 0,
    abs_val = abs(sample)
  )

ggplot(learning_df, aes(x = abs_val)) + geom_histogram()
```

 